### ISSUE TITLE
Confused whether this is a plugin or a variation of Fitnesse?

### ISSUE THREAD

**Issue by forceedge01** [nikoudel/easyfit#2]
This is classed as a plugin for FitNesse, but this package ships with a version of FitNesse? A plugin is meant to integrate with an existing instance of Fitnesse which could also be using other plugins. Is this truely a plugin?

**Comment by nikoudel** [comment]
It's a [fixture](http://fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.WritingAcceptanceTests.FixtureCode), i.e. kind of a plugin. Hasn't been in active use for years though, so I don't know how it works with the current version of FitNesse.
